redis:
  image: redis:alpine
  container_name: redis_cache
  ports:
    - "6379:6379"

testrunner:
  image: sageone/testrunner
  container_name: testrunner
  command: sh -c "while true; do echo 'Container is running..'; sleep 5; done"
  volumes:
    - ../:/code
  links:
    - redis

testrunner2:
  image: 522104923602.dkr.ecr.eu-west-1.amazonaws.com/sageone/jruby:20171218
  container_name: testrunner_jruby
  command: sh -c "while true; do echo 'Container is running..'; sleep 5; done"
  volumes:
    - ../:/code
  links:
    - redis

