source 'https://rubygems.org'

# Specify your gem's dependencies in cache_store_redis.gemspec
gemspec

platforms :ruby do
  gem 'oj', '3.2.0'
  gem 'json'
  gem 'pry'
end

platforms :jruby do
  gem 'json'
  gem 'pry-debugger-jruby'
end